version: "0.5"

processes:
  adampresleydev:
    command: air
    namespace: http:8081
    working_dir: ./cmd/adampresleydev
    readiness_probe:
      http_get:
        host: localhost
        port: 8081
        scheme: http
        path: /heartbeat
    liveness_probe:
      http_get:
        host: localhost
        port: 8081
        scheme: http
        path: /heartbeat
